services:
  frontend:
    build:
      context: .
      dockerfile: configs/Dockerfile
  web:
    build:
      context: .
      dockerfile: configs/nginx/Dockerfile
    ports:
      - 8080:80
    depends_on:
      - frontend